<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'CACLIUM CFPK',
                'nutrients' => 'SiO2 83%, + Te/Micro',
                'landType' => 'Semua jenis lahan',
                'age' => 'Semua umur',
                'condition' => 'Buah Sehat atau Normal',
                'price' => 360000, // Disimpan sebagai integer (tanpa Rp. dan titik)
                'benefit' => 'Penggemburan dan penyuburan tanah, meningkatkan pertumbuhan akar, batang, daun, pembungaan, dan pembentukan buah',
                'image' => 'https://drive.google.com/uc?id=1NL6IDfgOy0otXTO8XH5wSSBNRQa0bC3R',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Calcium Granular',
                'nutrients' => 'CaO 26%, CaCO3 47%, MgO 20%, K2O 10%, S 5%, SiO2 10%, + Te/Micro',
                'landType' => 'Semua jenis lahan',
                'age' => 'Semua umur',
                'condition' => 'Buah Sehat atau Normal',
                'price' => 310000,
                'benefit' => 'Menstabilkan pH tanah, perbanyakan nutrisi, dan menstabilkan pembuahan',
                'image' => 'https://drive.google.com/uc?id=1s_CLVeZK5bU0psSxce9ihVIIxYSVzIQG',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Calcium M 100 Powder',
                'nutrients' => 'CaO 35%, CaCO3 61%, MgO 21%, K2O 6%, S 0.10%, Fe2O3 1882 mg/kg, CuO 2.80 mg/kg, + Te/Micro',
                'landType' => 'Semua jenis lahan',
                'age' => 'Semua umur',
                'condition' => 'Buah Sehat atau Normal',
                'price' => 210000,
                'benefit' => 'Menetralkan pH tanah, memperbaiki struktur kimia tanah, dan meningkatkan bobot buah',
                'image' => 'https://drive.google.com/uc?id=1wlyAoGAd9T6_h6QwpUZRbo8Hlerd5Ob-',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CRP PAUS',
                'nutrients' => 'CaO 42%, CaCO3 86%, P2O5 5%, K2O 3%, S 5%, SiO2 2%, + Te/Micro',
                'landType' => 'Lahan darat',
                'age' => '10-15 tahun, 15-20 tahun',
                'condition' => 'Buah Sehat atau Normal',
                'price' => 260000,
                'benefit' => 'Pupuk perbanyakan nutrisi tanah dan pembesaran buah',
                'image' => 'https://drive.google.com/uc?id=11ztugaQb7v7zWKW-XuxWsWPA90yNS6At',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KSP PLUS 31',
                'nutrients' => 'K2O 27%, P2O5 31%, Sodium Humat 2%, + Te/Micro',
                'landType' => 'Semua jenis lahan',
                'age' => '5-10 tahun, 10-15 tahun',
                'condition' => 'Buah Tidak Sehat',
                'price' => 610000,
                'benefit' => 'Mempercepat perbaikan tanah, pertumbuhan perakaran, batang, dan pembesaran buah',
                'image' => 'https://drive.google.com/uc?id=1zilCqPnBDXiIrgy6knt-XMIHkC-ozwq-',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Magsul - Powder',
                'nutrients' => 'MgO 26%, SiO2 4%, S 20%, + Te/Micro',
                'landType' => 'Semua jenis lahan',
                'age' => 'Semua umur',
                'condition' => 'Buah Tidak Sehat',
                'price' => 210000,
                'benefit' => 'Metabolisme fosfat, respirasi tanaman, aktivitas enzim, dan fotosintesis',
                'image' => 'https://drive.google.com/uc?id=19VsGE1-ijQ6OZ4srcOm9tDlwOm_8LLLZ',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Magsul - Granular',
                'nutrients' => 'MgO 26%, SiO2 4%, S 20%, + Te/Micro',
                'landType' => 'Semua jenis lahan',
                'age' => 'Semua umur',
                'condition' => 'Buah Tidak Sehat',
                'price' => 230000,
                'benefit' => 'Metabolisme fosfat, respirasi tanaman, aktivitas enzim, dan fotosintesis',
                'image' => 'https://drive.google.com/uc?id=1RMwkgarYOR6WSMjW7sSV2McXpbsJNwQ1',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Magsili - Powder',
                'nutrients' => 'MgO 24 %, SiO2 43 %, Al2O3 4.51 %, + Te/Micro',
                'landType' => 'Semua jenis lahan',
                'age' => 'Semua umur',
                'condition' => 'Buah Sehat atau Normal',
                // Mengambil angka dari 'Powder Rp.220.000'
                'price' => 220000,
                'benefit' => 'Menetralkan struktur tanah, perbaikan pertumbuhan tanaman dan pembesaran buah',
                'image' => 'https://drive.google.com/uc?id=11vai4C3Z07IOh0tgBsLtxfK-yacs03RG',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Magsili - Granular',
                'nutrients' => 'MgO 24 %, SiO2 43 %, Al2O3 4.51 %, + Te/Micro',
                'landType' => 'Semua jenis lahan',
                'age' => 'Semua umur',
                'condition' => 'Buah Sehat atau Normal',
                // Mengambil angka dari 'Granular Rp.240.000'
                'price' => 240000,
                'benefit' => 'Menetralkan struktur tanah, perbaikan pertumbuhan tanaman dan pembesaran buah',
                'image' => 'https://drive.google.com/uc?id=1nXsYNgMcbr9nT1XFsHZZ2zXnyRQ_YYG0',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nitroganik',
                'nutrients' => 'N 20%, K2O 6%, S 15%, MgO 2%, CaO 15%, CaCO3 27%, SiO2 15%, + Te/Micro',
                'landType' => 'Semua jenis lahan',
                'age' => 'Semua umur',
                'condition' => 'Buah Sehat atau Normal',
                'price' => 390000,
                'benefit' => 'Mempercepat perbaikan pertumbuhan akar, batang, pelepah, daun, dan buah',
                'image' => 'https://drive.google.com/uc?id=1TVpuieWmjqjiXPdbW6rrguJxW5YsYXse',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NPK 6-12-22',
                'nutrients' => 'N2, P2O5, K2O, S, CaO, CaCO3, MgO, SiO2, + Te/Micro',
                'landType' => 'Lahan gambut',
                'age' => '5-10 tahun, 10-15 tahun',
                'condition' => 'Buah Sehat atau Normal',
                'price' => 420000,
                'benefit' => 'Menyeimbangkan unsur hara, meningkatkan ketahanan tanaman',
                'image' => 'https://drive.google.com/uc?id=1TGieaSAllcgFItL2Kx9yXP-i-ybFSk34',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NPK 12-12-18',
                'nutrients' => 'N2 12%, P2O5 12%, K2O 18%, MgO 3%, CaO 11%, CaCO3 19%, SiO2 6%, S 3%, + Te/Micro',
                'landType' => 'Lahan gambut',
                'age' => '<5 tahun, 5-10 tahun',
                'condition' => 'Buah Sehat atau Normal & Sakit',
                'price' => 440000,
                'benefit' => 'Perbanyakan dan pembesaran buah',
                'image' => 'https://drive.google.com/uc?id=17dUv316Cpa7vifwi89j7QFyWgLKNP5hF',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                
                'name' => 'NPK 13-18-27',
                'nutrients' => 'N2 13%, P2O5 8%, K2O 27%, MgO 3%, SiO2 6%, S 4%, CaO 10%, CaCO3 20%, + Te/Micro',
                'landType' => 'Lahan darat',
                'age' => '10-15 tahun, 15-20 tahun',
                'condition' => 'Buah Sehat atau Normal',
                'price' => 470000,
                'benefit' => 'Perbanyakan dan pembesaran buah',
                'image' => 'https://drive.google.com/uc?id=17hLygqtsNLNzX3jE515fCidQBr2Goswa',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NPK PLUS 12',
                'nutrients' => 'N2 2%, P2O5 4%, K2O 6%, S 2%, CaO 34%, CaCO3 61%, MgO 19%, + Te/Micro',
                'landType' => 'Lahan darat',
                'age' => '5-10 tahun, 10-15 tahun',
                'condition' => 'Buah Sehat atau Normal',
                'price' => 280000,
                'benefit' => 'Pupuk perbanyakan nutrisi tanah dan pembesaran buah',
                'image' => 'https://drive.google.com/uc?id=1yig0XQ8CwSSSarq7pwipU3VioS8GBB-H',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NPK PLUS 17',
                'nutrients' => 'N2 2%, P2O5 4%, K2O 11%, S 2%, CaO 31%, CaCO3 56%, MgO 18%, + Te/Micro',
                'landType' => 'Lahan berpasir',
                'age' => '5-10 tahun, 10-15 tahun',
                'condition' => 'Buah Sehat atau Normal',
                'price' => 310000,
                'benefit' => 'Pupuk perbanyakan nutrisi tanah dan pembesaran buah',
                'image' => 'https://drive.google.com/uc?id=1Tlob52ct-Np6J6gbU4z-wXA1KOlsW4eS',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NPK TRIPPLE 15',
                'nutrients' => 'N2 15%, P2O5 15%, K2O 15%, MgO 8%, CaO 12%, + Te/Micro',
                'landType' => 'Semua jenis lahan',
                'age' => 'Semua umur',
                'condition' => 'Buah Sehat atau Normal',
                'price' => 470000,
                'benefit' => 'Menyeimbangkan unsur hara dan meningkatkan pertumbuhan tanaman',
                'image' => 'https://drive.google.com/uc?id=1Wf8NiAu49Fit8WDSpXkmZ7HJ0_GU2NoS',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // Duplikat ID di data asli, dipertahankan
                'name' => 'PHOSUL',
                'nutrients' => 'P2O5 21%, S 8%, MgO 10%, + Te/Micro',
                'landType' => 'Semua jenis lahan',
                'age' => '5-10 tahun, 10-15 tahun',
                'condition' => 'Buah Sehat atau Normal',
                'price' => 410000,
                'benefit' => 'Pupuk perbaikan tanah, pertumbuhan perakaran dan batang, serta menstabilkan pembuahan',
                'image' => 'https://drive.google.com/uc?id=1yHxuZalSnGofq_8Is17x7lhWwH9AIoBx',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [// Duplikat ID di data asli, dipertahankan
                'name' => 'SUPER NITREA 2',
                'nutrients' => 'N2, K2O, S, CaO, CaCO3, MgO, SiO2 / Zeolite, + Te/Micro',
                'landType' => 'Semua jenis lahan',
                'age' => '5-10 tahun, 10-15 tahun',
                'condition' => 'Buah Sehat atau Normal',
                'price' => 390000,
                'benefit' => 'Meningkatkan daya serap nutrisi tanah dan pertumbuhan akar',
                'image' => 'https://drive.google.com/uc?id=1llOaQvN14hYtCTVQzwKJLcoPxBrr21fw',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SS/AMOPHOS',
                'nutrients' => 'N2 16%, P2O5 20%, S 13%, SiO2 4%, + Te/Micro',
                'landType' => 'Lahan gambut',
                'age' => '<5 tahun, 5-10 tahun',
                'condition' => 'Buah Tidak Sehat',
                'price' => 480000,
                'benefit' => 'Perbaikan pertumbuhan & peningkatan pembuahan',
                'image' => 'https://drive.google.com/uc?id=1c4Se4Vm0VJoYahTX8L_bct285xND24ex',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ZKAL',
                'nutrients' => 'S 15%, K2O 30%, MgO 13%, CaO 7%, CaCO3 12%, + Te/Micro',
                'landType' => 'Semua jenis lahan',
                'age' => '5-10 tahun, 10-15 tahun',
                'condition' => 'Buah Tidak Sehat',
                'price' => 380000,
                'benefit' => 'Pupuk perbaikan tanah, perbanyakan nutrisi, dan menstabilkan pembuahan',
                'image' => 'https://drive.google.com/uc?id=1gVKYYdGhPPv20LggHvf5jQD-aG1LvD0A',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert data ke tabel 'products'
        DB::table('products')->insert($products);
    }
}
